title: 和歌山県串本町
description: 和歌山県串本町内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vSiJlPyDWEeFHFAMsHbm_PrCetVQoJ9Pag3GZXBtkC0bMrly7vlHZd-K_z9-tOOoJzbpQKK7q0IYPam/pub?gid=0&single=true&output=csv
repository: https://github.com/iemeshi/kushimoto.iemeshi.jp
form_url: https://docs.google.com/forms/d/e/1FAIpQLSdjDvfWD5pIuxYiIgVBBwmsfd8-6sgActbeMOm2450dRfZroQ/viewform
